language: python
python: 3.5
service: elasticsearch
env:
  matrix:
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35
cache:
  directories:
    - $HOME/.cache/pip
before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.3.0.deb && sudo dpkg -i --force-confnew elasticsearch-5.3.0.deb && sudo service elasticsearch restart
install: pip install docutils tox
script: tox
